// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtwsqjgguecoknqqulnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0d3NxamdndWVjb2tucXF1bG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0OTM5MzIsImV4cCI6MjA4MzA2OTkzMn0.Z5M4soEr50QGblO_o-_bI5KSUWc5PP3ijKF0v9MMPIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
